[package]
name = "redis-concentrator"
version = "0.0.1"
authors = ["Emeric MARTINEAU"]
edition = "2018"
description = "Redis Concentrator is tool to easly connect your application to Redis without know his infrastructure."
repository = "..."
readme = "README.md"
keywords = ["redis", "sentinel", "cluster"]
license = "Apache-2.0"
license-file = "LICENSE-APACHE"
maintenance = { status = "actively-developed" }